use_frameworks!

platform :ios, '15.0'

target 'SimpleMagnifyingView_Example' do
  pod 'SimpleMagnifyingView', :path => '../'

  target 'SimpleMagnifyingView_Tests' do
    inherit! :search_paths

    
  end
end
